import type { NextPage } from "next";
import Head from "next/head";
import FormNavigation from "grupo-04/components/login/formNavigation";

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Digital Money House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FormNavigation/>
    </>
  );
};

export default Login;
