import { Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";

const Register: NextPage = () => {
  return (
    <>
      <Head>
        <title>DMH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography>Register</Typography>
    </>
  );
};

export default Register;
