import { Typography } from "@mui/material";
import LayoutAuth from "grupo-04/components/layout/layout-auth";
import FormRegister from "grupo-04/components/register/formRegister.component";
import type { NextPage } from "next";
import Head from "next/head";

const Register: NextPage = () => {
  return (
    <>
      <Head>
        <title>Digital Money House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAuth>
        <FormRegister />
      </LayoutAuth>
    </>
  );
};

export default Register;
