import { Box, Button, Stack, Typography } from "@mui/material";
import type { NextPage } from "next";
import NextLink from "next/link";
import Head from "next/head";

const Register: NextPage = () => {
  return (
    <>
      <Head>
        <title>DMH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack alignItems="center" justifyContent="center" height="100%">
        <Typography variant="h2" fontWeight={600} letterSpacing={2}>
          Registro Exitoso
        </Typography>
        <Box
          component="img"
          alt="icon"
          src={"./Check.svg"}
          sx={{
            marginTop: 4,
            maxWidth: 95,
          }}
        />
        <NextLink href="/login">
          <Button
            variant="contained"
            sx={{ width: 350, height: 60, marginTop: 7 }}>
            Continuar
          </Button>
        </NextLink>
      </Stack>
    </>
  );
};

export default Register;
