import { Box, Button, Stack, Typography } from "@mui/material";
import type { NextPage } from "next";
import NextLink from "next/link";
import Head from "next/head";
import LayoutBasic from "grupo-04/components/layout/layout-basic";

const Register: NextPage = () => {
  return (
    <>
      <Head>
        <title>Digital Money House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutBasic>
        <Stack alignItems="center" justifyContent="center" height="100%">
          <Typography variant="h3" fontWeight={600} letterSpacing={2} sx={{color: "#fff"}}>
            Registro Exitoso
          </Typography>
          <Box
            component="img"
            alt="icon"
            src={"./Check.svg"}
            sx={{
              marginTop: 4,
              maxWidth: 95,
            }}
          />
          <NextLink href="/login">
            <Button
              variant="contained"
              sx={{ width: 350, height: 60, marginTop: 7 }}>
              Continuar
            </Button>
          </NextLink>
        </Stack>
      </LayoutBasic>
    </>
  );
};

export default Register;
