import type { NextPage } from "next";
import Head from "next/head";
import { Typography } from "@mui/material";
import LayoutGeneral from "grupo-04/components/layout/layout-general";
import BodySingle from "grupo-04/components/layout/general/general-body";
import HomeImage from "grupo-04/components/home/img-home";

const Home: NextPage = () => {
  return (
    <LayoutGeneral>
    
      <Head>
        <title>DMH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <BodySingle>
            <HomeImage></HomeImage>
          </BodySingle>

      </LayoutGeneral>
  );
};

export default Home;
