import type { NextPage } from "next";
import Head from "next/head";
import { Typography } from "@mui/material";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>DMH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography>Home</Typography>
    </>
  );
};

export default Home;
